### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by tpelosi** [akalp/bs5-nav-tree#1]
Tried everything, but did not get this error:

tree.js:73 Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at http://127.0.0.1:8000/static/js/tree.js:73:12
    at NodeList.forEach (<anonymous>)
    at init (http://127.0.0.1:8000/static/js/tree.js:49:48)
    at new NavTree (http://127.0.0.1:8000/static/js/tree.js:156:3)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8000/women-rights-america/:4769:20)

**Comment by tpelosi** [comment]
Apparently, the issue is to have the tree inside a Bootstrap Modal. Outside the modal it works just fine.

**Comment by akalp** [comment]
Hello @tpelosi,
I had started to develop a new version before you opened this issue and I tested your case in the new version. There doesn't seem to be a problem now. If you have any problems, you can be sure that I will try to help. 
Good day, good coding.
