### ISSUE TITLE
Less issue more compliment 

### ISSUE THREAD

**Issue by joomkit** [akalp/bs5-nav-tree#3]
This is a great piece of work. Thank you.
I wanted to move the icons from left to the right so changed line 100 to append to the end
 li_container.appendChild(icon_container)

Be nice to have in config:)
Also be good to have the icons linked too

**Comment by akalp** [comment]
i'll add it to the config asap 👍🏻 
thank you for the praise 🤘🏻

**Comment by akalp** [comment]
Resolved with [the commit](https://github.com/akalp/bs5-nav-tree/commit/7d0e4642f734dd89e06888302e00a316934095dd).

**Comment by akalp** [comment]
A little fix -> [moved icon from li_container to suffix_container](https://github.com/akalp/bs5-nav-tree/commit/ddae665468a63f212ac6ef202ffa5d28c55351b0)
